# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: R commands for BIOL2131/BIOL6004
author: Sasha Mikheyev
logo: logo.png
copyright: "2022"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Information about where the book exists on the web
repository:
  url: https://github.com/mikheyev/ecology-r-code  # Online location of your book
  path_to_book: /  # Optional path to your book, relative to the repository root
  branch: gh-pages  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false

exclude_patterns: [README.md]

sphinx:
    config:
      html_theme_options:
        use_download_button: false
